name: Release

on:
  push:
    tags: ["*.*.*"]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Release
      env:
        FILE_ENCRYPTION_PASSPHRASE: ${{ secrets.FILE_ENCRYPTION_PASSPHRASE }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      run: |
        export SMALLD_VERSION="$(git describe --dirty --tags)"
        export MAVEN_OPTS="-Drevision=$SMALLD_VERSION -Dproperty=revision -DnewVersion=$SMALLD_VERSION -DgenerateBackupPoms=false"
        openssl aes-256-cbc -d -in etc/codesigning.asc.enc -out etc/codesigning.asc -k $FILE_ENCRYPTION_PASSPHRASE
        gpg --batch --fast-import etc/codesigning.asc
        mvn -s etc/settings.xml -B versions:set-property verify deploy -P release
