name: Sonar

on:
  push:
    branches: [ master ]

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - run: echo ::set-env name=SMALLD_VERSION:"$(git describe --dirty --tags)-SNAPSHOT"
    - run: echo ::set-env name=MAVEN_OPTS:"-Drevision=$SMALLD_VERSION -Dproperty=revision -DnewVersion=$SMALLD_VERSION -DgenerateBackupPoms=false"'
    - name: Run SonarCloud
      run: > 
          mvn -B sonar:sonar
          -Dsonar.organization=ianagbip1oti-github
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
     
